### ISSUE TITLE
aplikacja nic nie robi

### ISSUE THREAD

**Issue by librowski** [Adimus11/smoke-test-action#1]

**Comment by adimus11** [comment]
Hi Jan, It's nice that this piece of code interested you. In fact, it does a lot, you can use this as an intermediate step in your Github Actions Workflow to perform smoke tests before deploying your solution.  

It works  also pretty well with diagnosing problems with VW Golf IV

**Comment by librowski** [comment]
Hello, thank you for a quick and very informative response. Issue resolved!
It should definitely appear in README so other programming wariaciks can easily contribute to this amazing piece of opensource software.
I hope it's just a beginning of a great journey from a MVP with huge potential to lucrative start-up.
Good job, keep it up :fire:
